name: docker gittest series CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the gitTest/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/gitTest -v ${{ github.workspace }}/_site:/srv/gitTest/_site \
        gitTest/builder:latest /bin/bash -c "chmod 777 /srv/gitTest && gitTest build --future"
